### ISSUE TITLE
Front End Web Development Track Courses to be Completed

### ISSUE THREAD

**Issue by tatjana-burdett** [tatjana-burdett/Treehouse#2]
## TODO

*Courses left to complete the Treehouse Front End Web Development Track*

* [] HTML Basics
* [] CSS Basics
* [] Debugging CSS with Chrome DevTools
* [] CSS Layout Basics
* [] Responsive Layouts
* [] CSS Flexbox Layout
* [] HTML Forms
* [] CSS Selectors
* [] JavaScript and the DOM
* [] Bootstrap 4 Basics
* [] Introduction to Front End Performance Optimization
* [] HTML Tables
* [] HTML Video and Audio
* [] Create a Media Player with MediaElement.js
* [] AJAX Basics
* [] Asynchronous Programming with JavaScript
* [] Working with the Fetch API
* [] Object-Oriented JavaScript
* [] Web Accessibility Compliance
* [] Website Optimization

:octocat: 🥳 :metal: :sparkles:

cc @rdburdett
